# Numpy assignment
- Different tasks will be detailed by comments or text.
- For further reference and resources, it's advised to check out the NumPy documentation.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [22]:
# Create a 1-dimensional NumPy array using np.array()
a1 = np.array([1,2,3,4,5])

# Create a 2-dimensional NumPy array using np.array()
a2 = np.array([[1,2,3],[3,4,5]])  

In [9]:
# Attributes of 1-dimensional array (shape, number of dimensions, data type, size and type)
print("Shape:", a1.shape)
print("Number of dimensions:", a1.ndim)
print("Size:", a1.size)
print("Type:", a1.dtype)

Shape: (5,)
Number of dimensions: 1
Size: 5
Type: int32


In [10]:
# Attributes of 2-dimensional array
print("Shape:", a2.shape)
print("Number of dimensions:", a2.ndim)
print("Size:", a2.size)
print("Type:", a2.dtype)

Shape: (2, 3)
Number of dimensions: 2
Size: 6
Type: int32


In [11]:
# Create an array of shape (5, 5) with only ones
a3 = np.ones((5,5), np.int64)
a3

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int64)

In [14]:
# Create an array of shape (3, 3, 5) with only zeros
a4 = np.zeros((3,3,5), np.int64)
a4

array([[[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]]], dtype=int64)

In [15]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
a5 = np.random.randint(0, 10, (7,2), np.int64 )
a5

array([[2, 1],
       [0, 2],
       [6, 1],
       [3, 8],
       [3, 6],
       [1, 8],
       [5, 6]], dtype=int64)

In [16]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
a6 = np.random.rand( 3,5 )
a6

array([[0.74910199, 0.28450563, 0.68882332, 0.66145083, 0.97390536],
       [0.9449761 , 0.75276625, 0.83219186, 0.22353561, 0.86918386],
       [0.54136395, 0.98210472, 0.68258731, 0.13813069, 0.42483586]])

In [21]:
# Create an array of normally distributed random numbers
a7 = np.random.randn(5)
a7

array([ 1.46564877, -0.2257763 ,  0.0675282 , -1.42474819, -0.54438272])

In [17]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
a8 = np.random.rand(4,6)
a8

array([[0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864,
        0.15599452],
       [0.05808361, 0.86617615, 0.60111501, 0.70807258, 0.02058449,
        0.96990985],
       [0.83244264, 0.21233911, 0.18182497, 0.18340451, 0.30424224,
        0.52475643],
       [0.43194502, 0.29122914, 0.61185289, 0.13949386, 0.29214465,
        0.36636184]])

In [18]:
# Copy the code from the cell above and run it again
np.random.seed(42)
a9 = np.random.rand(4,6)
a9

array([[0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864,
        0.15599452],
       [0.05808361, 0.86617615, 0.60111501, 0.70807258, 0.02058449,
        0.96990985],
       [0.83244264, 0.21233911, 0.18182497, 0.18340451, 0.30424224,
        0.52475643],
       [0.43194502, 0.29122914, 0.61185289, 0.13949386, 0.29214465,
        0.36636184]])

In [19]:
# Find the 0'th index of the latest array you created
print(a9[0][0])

0.3745401188473625


In [20]:
# Get the first 2 rows of latest array you created
r1 = a9[0]
r2 = a9[1]
print( r1,"\n", r2 )

[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864 0.15599452] 
 [0.05808361 0.86617615 0.60111501 0.70807258 0.02058449 0.96990985]


In [23]:
# Get the first 2 values of the first 2 rows of the latest array
r1v1 = r1[0]
r2v1 = r2[0]
print(r1v1,"\n",r2v1)

0.3745401188473625 
 0.05808361216819946


In [24]:
# Create a random array of numbers between 0 & 10 and an array of ones both of size (3, 5), save them both to variables
b1 = np.random.randint(0, 10, (3,5), np.int64)
b2 = np.ones( (3,5), np.int64)

In [25]:
# Add the two arrays together
b3 = b1+b2
b3

array([[ 3,  7,  5,  9,  7],
       [ 2,  4,  9,  2, 10],
       [ 9, 10,  5,  2,  4]], dtype=int64)

In [26]:
# Create another array of ones of shape (5, 3)
b4 = np.ones( (5,3), np.int64 )

In [29]:
# Try add the array of ones and the other most recent array together # You can anticipate an error
b3 + b4

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

In [30]:
# Do the same operation you just did but this time with a transpose on one array
b5 = b3 + np.transpose(b4)
b5

array([[ 4,  8,  6, 10,  8],
       [ 3,  5, 10,  3, 11],
       [10, 11,  6,  3,  5]], dtype=int64)

In [31]:
# Take the latest array to the power of 2 using the python way
b5**2

array([[ 16,  64,  36, 100,  64],
       [  9,  25, 100,   9, 121],
       [100, 121,  36,   9,  25]], dtype=int64)

In [32]:
# Do the same thing with numpy way
np.power(b5,2)

array([[ 16,  64,  36, 100,  64],
       [  9,  25, 100,   9, 121],
       [100, 121,  36,   9,  25]], dtype=int64)

In [33]:
# Find the mean, min, max, standard deviation, variance of the latest array using np.mean()
b5mean = np.mean(b5)
b5max = np.max(b5)
b5min = np.min(b5)
b5std = np.std(b5)
b5var = np.var(b5)
print(b5mean)
print(b5max)
print(b5min)
print(b5std)
print(b5var)

6.866666666666666
11
3
2.9181424837652385
8.515555555555554


In [34]:
# Create two arrays of random integers between 0 to 10 one of size (3, 3) the other of size (3, 2)
c1 = np.random.randint(0,10, (3,3), np.int64)
c2 = np.random.randint(0,10, (3,2), np.int64)
print(c1)
print(c2)

[[6 7 2]
 [0 3 1]
 [7 3 1]]
[[5 5]
 [9 3]
 [5 1]]


In [35]:
# Perform a dot product on the two newest arrays you created
cdot = np.dot(c1,c2)
print(cdot)

[[103  53]
 [ 32  10]
 [ 67  45]]


In [36]:
# Create two arrays of random integers between 0 to 10 both of size (4, 3)
d1 = np.random.randint(0,10, (4,3), np.int64)
d2 = np.random.randint(0,10, (4,3), np.int64)

In [37]:
# Perform a hadamard product on the two newest arrays you created
dhad = np.multiply(d1,d2)
dhad

array([[81,  8, 72],
       [ 0, 56, 36],
       [64, 49,  0],
       [ 7, 28, 14]], dtype=int64)

In [38]:
# Perform a dot product on the two newest arrays you created # Error anticipated
ddot = np.dot(d1,d2)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

In [39]:
# Take the latest two arrays, perform a transpose on one of them and then perform a dot product on them both
ddot = np.dot( d1, np.transpose(d2) )
ddot

array([[161,  62,  79,  88],
       [131,  92,  73,  82],
       [160,  80, 113, 113],
       [ 97,  74,  36,  49]], dtype=int64)

In [40]:
# Create two arrays of random integers between 0 & 10 of the same shape and save them to variables
e1 = np.random.randint(0,10, 5)
e2 = np.random.randint(0,10, 5)

In [41]:
# Compare the two arrays with '>', '<=' and '==' 
print(e1>e2)
print(e1<=e2)
print(e1==e2)

[False False False False False]
[ True  True  True  True  True]
[False False False False False]


In [42]:
# Sort one of the arrays you just created in ascending order
np.sort(e1)

array([0, 0, 2, 2, 7])

In [43]:
# Sort the indexes of one of the arrays you just created
print( np.argsort(e2))

[0 2 4 1 3]


In [44]:
# Find the index with the maximum value in one of the arrays you've created
print( np.argmax(e2))

1


In [45]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.linspace(1,100,10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [46]:
# Find the indexes with the maximum values down the verticial axis of one of the arrays you created
np.argmax(c2,axis = 1)

array([0, 0, 0], dtype=int64)

In [47]:
# Find the indexes with the minimum values across the horizontal axis of one of the arrays you created
np.argmin(c1,axis = 0)

array([1, 1, 1], dtype=int64)